In [1]:
# Import Dependencies
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.ensemble import EasyEnsembleClassifier
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [5]:
# Load the data
file_path = Path('resources/healthy_lifestyle_city_2021.csv')
df = pd.read_csv(file_path)
df.head

<bound method NDFrame.head of                 City  Rank Sunshine hours(City)  \
0          Amsterdam     1                 1858
1             Sydney     2                 2636
2             Vienna     3                 1884
3          Stockholm     4                 1821
4         Copenhagen     5                 1630
5           Helsinki     6                 1662
6            Fukuoka     7                 2769
7             Berlin     8                 1626
8          Barcelona     9                 2591
9          Vancouver    10                 1938
10         Melbourne    11                 2363
11           Beijing    12                 2671
12           Bangkok    13                 2624
13      Buenos Aires    14                 2525
14           Toronto    15                 2066
15            Madrid    16                 2769
16           Jakarta    17                 2983
17             Seoul    18                 2066
18         Frankfurt    19                 1662
19            Geneva    20                    -
20          Tel Aviv    21                 3311
21          Istanbul    22                 2218
22             Cairo    23                 3542
23            Taipei    24                 1405
24       Los Angeles    25                 3254
25            Mumbai    26                 2584
26            Boston    27                 2634
27            Dublin    28                 1453
28             Tokyo    29                 1877
29           Chicago    30                 2508
30         Hong Kong    31                 1836
31          Shanghai    32                 1776
32          Brussels    33                 1546
33     San Francisco    34                 3062
34             Paris    35                 1662
35         Sao Paulo    36                 2003
36            Zurich    37                 1566
37            London    38                 1633
38      Johannesburg    39                 3124
39             Milan    40                 1915
40  Washington, D.C.    41                 2528
41          New York    42                 2535
42            Moscow    43                 1901
43       Mexico City    44                 2555

   Cost of a bottle of water(City) Obesity levels(Country)  \
0                            £1.92                  20.40%
1                            £1.48                  29.00%
2                            £1.94                  20.10%
3                            £1.72                  20.60%
4                            £2.19                  19.70%
5                            £1.60                  22.20%
6                            £0.78                   4.30%
7                            £1.55                  22.30%
8                            £1.19                  23.80%
9                            £1.08                  29.40%
10                           £1.57                  29.00%
11                           £0.26                   6.20%
12                           £0.22                  10.00%
13                           £0.57                  28.30%
14                           £1.09                  29.40%
15                           £1.30                  23.80%
16                           £0.21                   6.90%
17                           £0.59                   4.70%
18                           £1.95                  22.30%
19                           £2.62                  19.50%
20                           £1.63                  26.10%
21                           £0.15                  32.10%
22                           £0.16                  32.00%
23                           £0.57                   6.20%
24                           £1.52                  36.20%
25                           £0.15                   3.90%
26                           £1.39                  36.20%
27                           £1.40                  25.30%
28                           £0.76                   4.30%
29                           £1.20                  36.20%
30                           £0.75                   6.20%
31                           £0.29                   6.20%
32                           £2.11                  22.10%
33                           £1.60                  36.20%
34                           £1.95                  21.60%
35                           £0.44                  22.10%
36                           £3.20                  19.50%
37                           £1.16                  27.80%
38                           £0.59                  28.30%
39                           £1.15                  19.90%
40                           £1.45                  36.20%
41                           £1.32                  36.20%
42                           £0.41                  23.10%
43                           £0.45                  28.90%

    Life expectancy(years) (Country) Pollution(Index score) (City)  \
0                               81.2                         30.93
1                               82.1                         26.86
2                               81.0                         17.33
3                               81.8                         19.63
4                               79.8                         21.24
5                               80.4                         13.08
6                               83.2                             -
7                               80.6                         39.41
8                               82.2                         65.19
9                               81.7                         24.26
10                              82.1                         25.90
11                              75.4                         85.43
12                              74.1                         76.64
13                              75.9                         52.64
14                              81.7                         37.83
15                              82.2                         52.68
16                              68.5                         84.39
17                              81.3                         57.82
18                              80.6                         37.78
19                              82.6                         27.25
20                              81.9                         47.28
21                              74.7                         69.49
22                              70.7                         91.74
23                              75.4                         49.32
24                              78.8                         66.07
25                              67.3                         82.84
26                              78.8                         27.03
27                              80.5                         40.07
28                              83.2                         42.84
29                              78.8                         43.33
30                              75.4                         67.46
31                              75.4                         77.40
32                              80.4                         62.67
33                              78.8                         47.36
34                              81.8                         65.10
35                              73.9                         79.78
36                              82.6                         17.31
37                              80.4                         58.91
38                              56.3                         61.83
39                              82.7                         67.19
40                              78.8                         39.18
41                              78.8                         57.36
42                              69.5                         57.63
43                              76.4                         82.78

   Annual avg. hours worked  Happiness levels(Country)  \
0                      1434                       7.44
1                      1712                       7.22
2                      1501                       7.29
3                      1452                       7.35
4                      1380                       7.64
5                      1540                       7.80
6                      1644                       5.87
7                      1386                       7.07
8                      1686                       6.40
9                      1670                       7.23
10                     1712                       7.22
11                        -                       5.12
12                        -                       5.99
13                        -                       5.97
14                     1670                       7.23
15                     1686                       6.40
16                        -                       5.28
17                     1967                       5.87
18                     1386                       7.07
19                     1557                       7.56
20                     1898                       7.12
21                     1832                       5.13
22                        -                       4.15
23                        -                       5.12
24                     1779                       6.94
25                        -                       3.57
26                     1779                       6.94
27                     1772                       7.09
28                     1644                       5.87
29                     1779                       6.94
30                        -                       5.51
31                        -                       5.12
32                     1583                       6.86
33                     1779                       6.94
34                     1505                       6.66
35                        -                       6.37
36                     1557                       7.56
37                     1538                       7.16
38                        -                       4.81
39                     1718                       6.38
40                     1779                       6.94
41                     1779                       6.94
42                     1965                       5.54
43                     2137                       6.46

    Outdoor activities(City)  Number of take out places(City)  \
0                        422                             1048
1                        406                             1103
2                        132                             1008
3                        129                              598
4                        154                              523
5                        113                              309
6                         35                              539
7                        254                             1729
8                        585                             2344
9                        218                              788
10                       243                              813
11                       223                              261
12                       377                             1796
13                       246                             1435
14                       174                             1656
15                       216                             2491
16                       114                              833
17                       144                              389
18                        23                              551
19                        44                              444
20                       139                              420
21                       419                              934
22                       323                              250
23                       134                              717
24                       223                             1439
25                       187                             1183
26                        88                              588
27                       159                              659
28                       387                             5802
29                       171                             1320
30                       277                             1257
31                       108                              346
32                        55                              988
33                       242                             1031
34                       331                             4363
35                       158                             3355
36                        69                              538
37                       433                             6417
38                       194                              492
39                       110                             2396
40                        83                              744
41                       359                             3081
42                       322                             3206
43                       192                             1313

   Cost of a monthly gym membership(City)
0                                  £34.90
1                                  £41.66
2                                  £25.74
3                                  £37.31
4                                  £32.53
5                                  £35.23
6                                  £55.87
7                                  £26.11
8                                  £37.80
9                                  £31.04
10                                 £36.89
11                                 £38.62
12                                 £50.03
13                                 £22.45
14                                 £32.64
15                                 £34.54
16                                 £29.94
17                                 £43.03
18                                 £39.01
19                                 £70.00
20                                 £58.31
21                                 £16.97
22                                 £23.25
23                                 £34.76
24                                 £32.00
25                                 £19.54
26                                 £46.27
27                                 £37.35
28                                 £70.82
29                                 £41.14
30                                 £57.95
31                                 £44.68
32                                 £25.34
33                                 £65.13
34                                 £35.93
35                                 £16.07
36                                 £73.11
37                                 £42.71
38                                 £24.28
39                                 £53.49
40                                 £65.99
41                                 £64.66
42                                 £31.40
43                                 £41.99  >